# Generated by Django 2.0.5 on 2018-07-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0002_auto_20180701_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('born_date', models.DateField()),
                ('creation_day', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('nationality', models.ManyToManyField(to='countries.Country')),
            ],
        ),
    ]
