# Generated by Django 2.0.5 on 2018-07-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='nationality',
            new_name='nationalities',
        ),
    ]
