# Generated by Django 2.0.5 on 2018-07-11 17:55

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='color',
            field=colorful.fields.RGBColorField(),
        ),
    ]
