# Generated by Django 2.0.5 on 2018-06-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=3)),
                ('description', models.TextField(max_length=255)),
                ('classification', models.CharField(choices=[('A', 'Safe'), ('B', 'Less safe'), ('C', 'Unsafe'), ('D', 'More Unsafe')], default='C', max_length=1)),
            ],
        ),
    ]
