# Generated by Django 2.0.5 on 2018-07-01 19:02

from django.db import migrations, models
import django.db.models.deletion

#def create_continent(apps,schema_editor):
#    Continent = apps.get_model('continents', 'Continent')
#    Continent.objects.create(name='Asia', population=1365486654, color='#EE65EE')
#    Continent.objects.create(name='Antartida', population=55863, color='#000000')
#    Continent.objects.create(name='America', population=2680146, color='#ffff00')
#    Continent.objects.create(name='Oseania', population=7893258, color='#ee65dd')
#    Continent.objects.create(name='Europa', population=23654897, color='#f04261')
#    Continent.objects.create(name='Africa', population=130230, color='#f1d142')

class Migration(migrations.Migration):

    dependencies = [
        ('continents', '0001_initial'),
        ('countries', '0001_initial'),
    ]

    operations = [
#        migrations.RunPython(create_continent),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='continents.Continent'),
            preserve_default=False,
        ),
    ]
