# Generated by Django 2.0.5 on 2018-07-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20180701_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
